from __future__ import annotations

from typing import Protocol

from engineering_brain.domain.models import (
    AudioSelection,
    DerivedAudioArtifact,
    MediaInspection,
    SourceArtifact,
)


class AudioPipelineRepository(Protocol):
    def get_artifact(self, artifact_id: str) -> SourceArtifact: ...
    def get_media_inspection(self, inspection_id: str) -> MediaInspection: ...
    def find_audio_selection(
        self, artifact_id: str, inspection_id: str, stream_index: int
    ) -> AudioSelection | None: ...
    def create_audio_selection(self, selection: AudioSelection) -> None: ...
    def get_audio_selection(self, selection_id: str) -> AudioSelection: ...
    def find_derived_audio_artifact(
        self, selection_id: str, extractor: str, version: str, schema: str, config_json: str
    ) -> DerivedAudioArtifact | None: ...
    def create_derived_audio_artifact(self, derived: DerivedAudioArtifact) -> None: ...
    def get_derived_audio_artifact(self, derived_id: str) -> DerivedAudioArtifact: ...
