from __future__ import annotations

from typing import Protocol

from engineering_brain.domain.models import Author, Material, Source, SourceArtifact


class SourceRegistryRepository(Protocol):
    def initialize(self) -> None: ...

    def create_author(self, author: Author) -> None: ...

    def get_author(self, author_id: str) -> Author: ...

    def create_source(self, source: Source) -> None: ...

    def get_source(self, source_id: str) -> Source: ...

    def create_material(self, material: Material) -> None: ...

    def get_material(self, material_id: str) -> Material: ...

    def list_materials(self) -> list[Material]: ...

    def get_artifact(self, artifact_id: str) -> SourceArtifact: ...

    def attach_artifact(self, material_id: str, artifact: SourceArtifact) -> tuple[SourceArtifact, bool]: ...

    def artifacts_for_material(self, material_id: str) -> list[SourceArtifact]: ...
